### PR TITLE
Adjust in the function snapshot.all()

### PR DESCRIPTION
**Pull request by shazaum**
Use clearer function:

snap =  client.snapshot.all()
for snaps in snap:
   print snaps.name

### CODE REVIEW

**Comment by ajkavanagh** [comment]
@shazaum thanks for the PR.  Unfortunately, I don't understand what this is a) fixing or b) what the new feature is?

Please could you indicate if this is a fix to a bug report (and quote the bug report) or describe what the feature is more clearly, and why the existing implementation is inadequate.  Thanks.

**Comment by shazaum** [comment]
@ajkavanagh Ops...
What I did was list the snapshots of all the containers directly.
It is not to replace the current function.
Just one way to list all snapshots directly.

**Comment by shazaum** [comment]
Just a new feature.

**Comment by ajkavanagh** [comment]
@shazaum thanks for the clarification.  In this situation, unfortunately, this patch doesn't fit with the design of the library's API, and also breaks the existing API call.  So it can't currently be accepted.

The issues are:

1. It breaks the existing implementation of the `...snapshot.all()`.
2. It doesn't really map to a single API call.
3. It's fairly easy to implement as a function that calls the library.

One way to do this using the API is:

```python
client = pylxd.Client()
snapshots = []
for container in client.containers.all():
    snapshots.extend(container.snapshots.all())
print(", ".join(s.name for s in snapshots))
```

This will print the names of the snapshots if you snapshot them with a name that is useful:

```bash
lxc snapshot <container-name> <snapshot-name>
```

**Comment by shazaum** [comment]
I think the lib can deliver a function to show all the snapshots...
because you first have to say, I want all the containers, then ask for the snapshots.

**Comment by ajkavanagh** [comment]
I'm sorry but this isn't going to be added as the LXD RESTful API doesn't provide the an API to do this directly.  Exactly the same issue of 1. getting all the containers, 2. iterating through the containers to get the snapshots, would have to be implemented in the library.

i.e. there is no `client.snapshots.all()` equivalent API call, and so the library would have to manufacture it using the code noted above.  This isn't in the spirit/design of the library which is to map as closely as possible to the RESTful API at: https://github.com/lxc/lxd/blob/master/doc/rest-api.md

**Pull request closed without merging**
