### PR TITLE
Fixed missing support for PROJECT param in enevt() 

### PR DESCRIPTION
**Pull request by k3idii**
Fixed by adding additinal param into query string for /evens/ API endpoint

### CODE REVIEW

**Review by v3ss0n — APPROVED** [review]

**Review by v3ss0n — APPROVED** [review]
LGTM

**Comment by sparkiegeek** [comment]
Thanks for the contribution - this needs unit tests, and your commits need `Signed-off-by` in the commit message -

**Comment by v3ss0n** [comment]
why closed?

**Comment by sparkiegeek** [comment]
It's been a year and a half since the PR was opened, and has not followed the guidelines in https://pylxd.readthedocs.io/en/latest/contributing.html#requirements-to-merge-a-pull-request-pr

**Pull request closed without merging**
