### PR TITLE
Fix documentation

### PR DESCRIPTION
**Pull request by jpic**
Convert README from markdown to rst format, because the
docs/source/readme.rst file expect it, and also because it will render
better on PyPi without additionnal configuration.

Also, added notes about documentation and tests in the README, and
extracted its contents into the doc/ directory.

I can only suggest that a repo maintainer add it to readthedocs.org

There's a lot more I'd love to do, but that's at least something that builds, so that looks like kind of a requirement for any broader contribution to be considerable, what do you think ?

### CODE REVIEW

**Comment by jpic** [comment]
Ref #79

**Comment by jpic** [comment]
Thanks, I'll keep going on that B)

**Comment by pjones-d** [comment]
It is worth noting that the current instructions to build documentation with sphinx do not work. Setup.py complains about having no build_sphinx option.

> Documentation is maintained in the doc directory. It can be built with the python setup.py build_sphinx command.

**Comment by jpic** [comment]
```
$ python setup.py build_sphinx
running build_sphinx
[pbr] Writing ChangeLog
[pbr] Generating ChangeLog
[pbr] ChangeLog complete (0.0s)
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
Running Sphinx v1.4.1
loading pickled environment... done
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index

/home/jpic/env/src/pylxd/doc/source/index.rst:11: WARNING: toctree contains
reference to nonexisting document u'readme'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] usage

generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.
Running Sphinx v1.4.1
WARNING: while setting up extension sphinx.ext.autodoc: directive
'automodule' is already registered, it will be overridden
WARNING: while setting up extension sphinx.ext.autodoc: directive
'autoclass' is already registered, it will be overridden
WARNING: while setting up extension sphinx.ext.autodoc: directive
'autoexception' is already registered, it will be overridden
WARNING: while setting up extension sphinx.ext.autodoc: directive
'autodata' is already registered, it will be overridden
WARNING: while setting up extension sphinx.ext.autodoc: directive
'autofunction' is already registered, it will be overridden
WARNING: while setting up extension sphinx.ext.autodoc: directive
'automethod' is already registered, it will be overridden
WARNING: while setting up extension sphinx.ext.autodoc: directive
'autoattribute' is already registered, it will be overridden
WARNING: while setting up extension sphinx.ext.autodoc: directive
'autoinstanceattribute' is already registered, it will be overridden
loading pickled environment... done
building [mo]: all of 0 po files
building [man]: all source files
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] index

/home/jpic/env/src/pylxd/doc/source/index.rst:11: WARNING: toctree contains
reference to nonexisting document u'readme'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... pylxd.1 { installation usage contributing api }
build succeeded, 9 warnings.
```
​

**Comment by pjones-d** [comment]
Not working for me with the latest git clone using python 3.5.1.

```
(env) pjones@ThinkPad:~/Development/Node-Z/pylxd$ python setup.py build_sphinx
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'build_sphinx'
```
What does your setup.py / setup.cfg look like? I was able to build the sphinx documentation manually with the following:

`sphinx-build -b html doc/source/ doc/build/`

**Pull request merged**
