### PR TITLE
Add dict method which includes readonly attributes to the model.

### PR DESCRIPTION
**Pull request by pcdummy**
[See](https://github.com/pcdummy/saltstack-lxd-formula/commit/eed61b2617841fbf10400b3d499ef7145e25dffe) it in action

Signed-off-by: Rene Jochum <rene@jochums.at>

### CODE REVIEW

**Comment by rockstar** [comment]
Can you explain why we would need this? I realize you're using it elsewhere in another library, but I can't think of why this logic should live in pylxd. In general, even the `marshall` method is kind of a "private" method, in that it's not really part of the public/documented api, and generally you shouldn't even need to call it yourself.

**Comment by pcdummy** [comment]
For me this dict method is handy as i don't need to know which `__attributes__` are stored on a model and
its a easy method to convert any PyLXD object to a dict, which is nice for json/yaml output on salt.

I could write my own "object_to_dict" but then i need to inspect it or iterrate over obj.__attributes__ which i'm sure we both don't want.

**Comment by rockstar** [comment]
While I appreciate your effort, I'm not sure that this is really suited for pylxd. A complication comes from the fact that you're using the objects in a little different way than pylxd itself is. I don't think iterating over `__attributes__` in your code is unrealistic (and we've defined a pretty good framework for that). This code, itself, would be unused by pylxd itself.

**Comment by pcdummy** [comment]
So as a solution you encourage me to iterate over __attributes__, right?

**Pull request closed without merging**
