### PR TITLE
Consolidate ContainerState into pylxd.container

### PR DESCRIPTION
**Pull request by rockstar**
It didn't make sense to have it in its own module.

### CODE REVIEW

**Comment by jpic** [comment]
Kudos for setting up codecov, I love it ! Don't forget to install the browser extension to see coverage in github source, because it's awesome ^^

Fix for coverage example in rockstar/pylxd#1

:guitar:

**Comment by jpic** [comment]
LGTM, although I wish, as a developer, I could have my hands on the response variable.

**Comment by zulcss** [comment]
+1

**Comment by rockstar** [comment]
@jpic Could you expand on that? I've been really trying to hide the low-level I/O information from that (e.g. maybe it's just reading from a file, or a database, or using thrift TCP). If you've got a reason to need to request later, then we could explore that idea.

**Pull request merged**
